Repository mercuridi/starwatch, pull requests merged in 2025-07, with the labels that each got.

#37 31: Modified RDS config for public access
  .gitignore
  terraform/rds_tf/main.tf
  terraform/rds_tf/variables.tf
Labels: bug

#28 18: Schema script
  src/schema.sql
Labels: enhancement, infrastructure

#48 31: Fixed rds accessibility
  terraform/rds_tf/main.tf
Labels: bug

#45 43: Transform Script for the Weather API Pipeline
  src/extract_weather.py
  src/transform_weather.py
Labels: transform, infrastructure
